name: Integration
on:
  push:
    branches:
      - master
  
jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: preparation
        run: echo "Preparing to deploy ..."
    
      - name: checks out the repository
        uses: actions/checkout@v4
      
      - name: Make HTTP request
        uses: fjogeleit/http-request-action@v1
        with: 
          url: 'http://api.exchangeratesapi.io/v1/latest?access_key=${{ secrets.API KEY }}&symbols=USD,AUD,CAD,PLN,MON'
          method: GET
          customHeader: '{"Content-Type": "application/json"}'


      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Build our code"
        env:
          IMAGE_NAME: cyclobold123
          VERSION: newest
          USERNAME: syjjem093
        run: |
            docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
            docker push $USERNAME/$IMAGE_NAME:$VERSION