name: Integration
on:
  push:
    branches:
      - master
  
jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: preparation
        run: echo "Preparing to deploy ..."
    
      - name: checks out the repository
        uses: actions/checkout@v4
      
      # - name: Make HTTP request
      #   uses: fjogeleit/http-request-action@v1
      #   with: 
      #     url: 'http://api.exchangeratesapi.io/v1/latest?access_key=${{ secrets.API_KEY }}&symbols=USD,AUD,CAD,PLN,MON'
      #     method: GET
      #     customHeader: '{"Content-Type": "application/json"}'
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
            channel-id: 'C067BEE3G3H'
            # For posting a simple plain text message
            slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      


      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Build our code"
        env:
          IMAGE_NAME: cyclobold123
          VERSION: newest
          USERNAME: syjjem093
        run: |
            docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
            docker push $USERNAME/$IMAGE_NAME:$VERSION